/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 skatie.glb 
Author: Kaye (https://sketchfab.com/kaye-simonson)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/skatie-ae3181c81cf34876b187b353291a2f96
Title: Skatie
*/

import { useGLTF } from '@react-three/drei'

export function SkatieModel(props) {
  const { nodes, materials } = useGLTF('/skatie.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.399, 25.483, 0]} rotation={[Math.PI, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.trucks_kingpin_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_nut_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_pivotcup_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_baseplate_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_bushing_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_hanger_1_low_skatie_0.geometry} material={materials.skatie} />
      </group>
      <group position={[-1.709, -14.686, 0]} rotation={[0, 0, -0.721]}>
        <mesh geometry={nodes.wheel_screw_1_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.wheel_1_low_skatie_0.geometry} material={materials.skatie} />
      </group>
      <group position={[0.369, 25.483, 0]} rotation={[0, 0, Math.PI]} scale={0.32}>
        <mesh geometry={nodes.trucks_kingpin_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_nut_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_pivotcup_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_baseplate_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_bushing_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.trucks_hanger_2_low_skatie_0.geometry} material={materials.skatie} />
      </group>
      <group position={[-5.348, -19.728, 0]} rotation={[0, 0, -1.019]}>
        <mesh geometry={nodes.wheel_screw_2_low_skatie_0.geometry} material={materials.skatie} />
        <mesh geometry={nodes.wheel_2_low_skatie_0.geometry} material={materials.skatie} />
      </group>
      <group position={[16.617, 15.401, 0]} rotation={[0, 0, 1.542]}>
        <mesh geometry={nodes.wheel_screw_2_low_skatie_0_1.geometry} material={materials.skatie} />
        <mesh geometry={nodes.wheel_2_low_skatie_0_1.geometry} material={materials.skatie} />
      </group>
      <group position={[1.935, 3.402, 0]} rotation={[0, 0, 2.481]}>
        <mesh geometry={nodes.wheel_screw_1_low_skatie_0_1.geometry} material={materials.skatie} />
        <mesh geometry={nodes.wheel_1_low_skatie_0_1.geometry} material={materials.skatie} />
      </group>
      <mesh geometry={nodes.trucks_baseplate_screws_1_low_skatie_0.geometry} material={materials.skatie} />
      <mesh geometry={nodes.trucks_baseplate_screws_2_low_skatie_0.geometry} material={materials.skatie} />
      <mesh geometry={nodes.deck_low_skatie_0.geometry} material={materials.skatie} scale={[1, 1, 1.056]} />
    </group>
  )
}

useGLTF.preload('/skatie.glb')
