/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lighter.glb 
Author: Mark Peters (https://sketchfab.com/mark-peters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zippo-lighter-4096px2-9a9cdaf66429455d8dd47e1d2919eb63
Title: Zippo Lighter - 4096px²
*/

import { useGLTF } from '@react-three/drei'

export function LighterModel(props) {
  const { nodes, materials } = useGLTF('/lighter.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.LighterBody_Lighter_MTL_0.geometry} material={materials.Lighter_MTL} position={[-0.029, 2.85, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.95, 0.7, 2.85]} />
        <mesh geometry={nodes.LighterButton_Lighter_MTL_0.geometry} material={materials.Lighter_MTL} position={[-1.252, 3.966, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={13.152} />
        <mesh geometry={nodes.LighterHinge_Lighter_MTL_0.geometry} material={materials.Lighter_MTL} position={[1.45, 4.158, 0]} rotation={[-Math.PI / 2, 0.262, 0]} scale={10} />
        <mesh geometry={nodes.LighterTop_Lighter_MTL_0.geometry} material={materials.Lighter_MTL} position={[1.921, 3.521, 0]} rotation={[-Math.PI / 2, -Math.PI / 4, 0]} scale={10} />
        <mesh geometry={nodes.LighterWheel_Lighter_MTL_0.geometry} material={materials.Lighter_MTL} position={[-1.241, 4.522, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/lighter.glb')
