/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 skateboard.glb 
Author: Jackmcm (https://sketchfab.com/Jackmcm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skateboard-globe-down-in-flames-8dd79c785a4142e4a6e077567569e9c8
Title: Skateboard [ Globe: DOWN IN FLAMES ]
*/

import { useGLTF } from '@react-three/drei'

export function SkateboardModel(props) {
  const { nodes, materials } = useGLTF('/skateboard.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/skateboard.glb')
