/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tShirt.glb 
Author: GLEB GUBKIN (https://sketchfab.com/DIGITALMIND618)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fish-t-shirt-b2bf0e93920f42618fb0255e137a61c9
Title: fish t-shirt
*/

import { useGLTF } from '@react-three/drei'

export function TShirtModel(props) {
  const { nodes, materials } = useGLTF('/tShirt.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[15.015, 192.505, 92.552]} scale={4.075}>
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_1.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_2.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_3.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_4.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_5.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_6.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_7.geometry} material={materials.Shirt_Texture} />
          <mesh geometry={nodes.Animated_Shirt_Shirt_Texture_0_8.geometry} material={materials.Shirt_Texture} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tShirt.glb')
