export const heroArtwork = {
  image: "/featured-hero2.png",
  title: "Neon Saint",
  medium: "Featured portrait / hero artwork / apparel direction",
  tone: "glowing green, coral spikes, lacquer black",
};

export const works = [
  {
    id: 1,
    image: "/poster2.png",
    title: "Green Script Saint",
    medium: "Portrait painting / glyph typography / apparel direction",
    tone: "powder pink, electric green, deep blue hair",
    layout: "featured",
  },
  {
    id: 2,
    image: "/spray-paint8.png",
    title: "Red Ceremony",
    medium: "Outdoor mural / character wall / ornamental frame",
    tone: "red robe, ink black, burnt orange",
    layout: "wide",
  },
  {
    id: 3,
    image: "/spray-paint12.png",
    title: "Cult Island",
    medium: "Rolling door mural / storefront portrait",
    tone: "cream shutter, green signage, red lips",
    layout: "wide",
  },
  {
    id: 4,
    image: "/poster5.png",
    title: "Retry 999",
    medium: "Tall poster / character graphic / tag study",
    tone: "storm blue, acid green, candy orange",
    layout: "tall",
  },
  {
    id: 5,
    image: "/poster3.png",
    title: "Crow Altar",
    medium: "Poster painting / mythic figure / skull study",
    tone: "bone white, raven black, bruised blue",
    layout: "poster",
  },
  {
    id: 6,
    image: "/spray-paint9.png",
    title: "Night Phoenix",
    medium: "Wall mural / bird character / process scene",
    tone: "purple wing, white wall, ladder shadow",
    layout: "wide",
  },
  {
    id: 7,
    image: "/spray-paint10.png",
    title: "Blue Bird Study",
    medium: "Wall detail / animal portrait / spray paint",
    tone: "peacock blue, concrete gray, rust mark",
    layout: "square",
  },
  {
    id: 8,
    image: "/poster4.png",
    title: "Blonde Raven",
    medium: "Portrait painting / bird motif / tag panel",
    tone: "soft yellow, cobalt shadow, lime tag",
    layout: "poster",
  },
  {
    id: 9,
    image: "/spray-paint11.png",
    title: "Laughing Wall",
    medium: "Interior mural / character close-up / tag wall",
    tone: "mint green, helmet yellow, bubble pink",
    layout: "wide",
  },
  {
    id: 10,
    image: "/poster.png",
    title: "Palace on the Sea",
    medium: "Poster painting / typography / commercial parody",
    tone: "sea haze, yellow type, sunset red",
    layout: "poster",
  },
  {
    id: 11,
    image: "/spray-paint2.png",
    title: "Pink Treasure Room",
    medium: "Rolling door mural / public wall / symmetric scene",
    tone: "hot pink shutter, sky blue, gold crown",
    layout: "wide",
  },
  {
    id: 12,
    image: "/tshirt-paint.png",
    title: "Nuclear Bride",
    medium: "T-shirt print / poster graphic / character type",
    tone: "black grain, magenta type, mint skin",
    layout: "poster",
  },
  {
    id: 13,
    image: "/spray-paint4.png",
    title: "Guard Dog",
    medium: "Storefront mural / animal portrait / tag wall",
    tone: "butter yellow, chrome spikes, candy red",
    layout: "square",
  },
  {
    id: 14,
    image: "/spray-paint.png.png",
    title: "Mirror Tag",
    medium: "Canvas painting / portrait / graffiti study",
    tone: "fog green, blush pink, oxidized orange",
    layout: "square",
  },
  {
    id: 15,
    image: "/tshirt-paint2.png",
    title: "Rider Creature",
    medium: "Illustration / skateboard graphic direction",
    tone: "ink black, dirty pink, utility yellow",
    layout: "product",
  },
  {
    id: 16,
    image: "/spray-paint5.png",
    title: "Masked Guardian",
    medium: "Street mural / mask character / close crop",
    tone: "orange block, olive mask, cyan tag",
    layout: "wide",
  },
  {
    id: 17,
    image: "/spray-paint3.png",
    title: "Shop Cat",
    medium: "Rolling door mural / night storefront",
    tone: "electric blue, shutter black, warning yellow",
    layout: "wide",
  },
];

export const surfaces = [
  {
    id: "wall",
    label: "Wall",
    title: "Murals and painted rooms",
    copy: "Large pieces need distance, texture, and uneven light. The site uses wall-scale crops so the work feels physical before it becomes a product.",
  },
  {
    id: "wear",
    label: "Wear",
    title: "Shirts as moving canvases",
    copy: "His graphics already read like apparel: loud type, central icons, harsh contrast, and characters that survive motion.",
  },
  {
    id: "objects",
    label: "Object",
    title: "Skateboards and pocket pieces",
    copy: "The 3D section keeps the skateboard, shirt, and lighter as rotating proof that the artwork can live on real objects.",
  },
];

export const imageSpecs = [
  {
    id: "hero",
    label: "Hero wall image",
    size: "2400 x 1350 px",
    ratio: "16:9",
    image: "/p1.jpg",
    note: "Use a strong portrait or mural. Keep the face in the center-right area and reserve one dark side for the headline.",
  },
  {
    id: "poster",
    label: "Poster / shirt front",
    size: "1800 x 2400 px",
    ratio: "3:4",
    image: "/p4.jpg",
    note: "Best for type-heavy paintings and poster compositions. Preserve the border, title, and phone-number style text.",
  },
  {
    id: "square",
    label: "Archive card",
    size: "1800 x 1800 px",
    ratio: "1:1",
    image: "/p5.jpg",
    note: "Good for canvas photos and social previews. Crop after straightening the frame and preserving texture.",
  },
  {
    id: "object",
    label: "3D object texture",
    size: "2048 x 2048 px",
    ratio: "1:1 texture",
    image: "/p2.jpg",
    note: "Use clean scans or transparent PNGs. Avoid heavy shadows because the 3D lighting will add its own.",
  },
];
